version: '3.8'

services:

  web:
    container_name: todo_app
    image: todo_app
    logging:
      driver: "json-file"
      options:
          max-size: "500m"
          max-file: "10"
    deploy:
      restart_policy:
        condition: any
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
    depends_on:
      - db
    ports:
    - 8001:8000


  db:
    image: mysql:8.0.33
    container_name: todo_app_db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: todo_db
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: J1juQiiNM005EWTAYkme
      # MYSQL_ROOT_PASSWORD: J1juQiiNM005EWTAYkme
      MYSQL_ALLOW_EMPTY_PASSWORD: yes